<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ArticlesStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'code' => 'required|alpha_dash|unique:articles,code',
            'title' => 'required|min:5|max:100',
            'detail' => 'required|max:255',
            'body' => 'required',
            'published' => 'boolean'
        ];
    }

//    public function messages()
//    {
//        return parent::messages(); // TODO: Change the autogenerated stub
//    }
//
//    public function attributes()
//    {
//        return parent::attributes(); // TODO: Change the autogenerated stub
//    }
}
